#!/usr/bin/python3

import sys
import urllib.parse
import urllib.request

APPLICATION = "pingme"
PROWL_API_KEY = "your_api_key_here"

def get_input():
    if not sys.stdin.isatty():

        if sys.argv[1:]:
            print("Error: Both arguments and pipe input were received")
            exit(1)
        else:
            user_input = " ".join(sys.argv[1:])

        for line in sys.stdin:
            user_input = line.rstrip('\n')
            print('Read from stdin: "{}"!'.format(user_input))
    else:
        user_input = " ".join(sys.argv[1:])

    return user_input


def prowl(message, apikey=PROWL_API_KEY, application=APPLICATION, user_input=get_input()):
    params = {"apikey": PROWL_API_KEY,
              "application": application,
              "description": user_input}
    encoded_params = urllib.parse.urlencode(params).encode()

    req = urllib.request.Request("https://api.prowlapp.com/publicapi/add", data=encoded_params, method="POST")
    urllib.request.urlopen(req)

def main():
    prowl(message=get_input())

if __name__ == "__main__":
    main()
