#!/usr/bin/python3

import argparse
import sys
import urllib.error
import urllib.parse
import urllib.request

APPLICATION = "pingme"
PROWL_API_KEY = "your_api_key_here"
MESSAGE = ""

parser = argparse.ArgumentParser()
parser.add_argument("-t", help="Title for your notification")
parser.add_argument("message", nargs=argparse.REMAINDER)
args = parser.parse_args()

if args.message:
    MESSAGE = " ".join(args.message)
if args.t:
    APPLICATION = args.t

def get_input():
    if not sys.stdin.isatty():

        if MESSAGE:
            sys.stderr.write("Error: Both arguments and pipe input were received\n")
            exit(1)
        else:
            user_input = " ".join(sys.argv[1:])

        for line in sys.stdin:
            user_input = line.rstrip('\n')
            print('Read from stdin: "{}"!'.format(user_input))
    else:
        user_input = MESSAGE

    return user_input


def prowl(message, apikey=PROWL_API_KEY, application=APPLICATION):
    print("Sending message from '{}': {}".format(application, message))

    params = {"apikey": PROWL_API_KEY,
              "application": application,
              "description": message}
    encoded_params = urllib.parse.urlencode(params).encode()

    req = urllib.request.Request("https://api.prowlapp.com/publicapi/add", data=encoded_params, method="POST")
    try:
        urllib.request.urlopen(req)
        print("Message sent!")
    except:
        raise

def main():
    MESSAGE = get_input()
    try:
        prowl(message=MESSAGE)
        print('Sent message "{}"'.format(MESSAGE))
    except urllib.error.HTTPError as err:
        if err.code == 401:
            sys.stderr.write("Error: API key not authorized!\n")
        else:
            raise


if __name__ == "__main__":
    main()
